---
title: "hw1 409"
date: "2021/1/12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,warning=FALSE,message=FALSE}
dailydata=read.table('eurdaily.txt')
attach(dailydata)
dailydata=na.omit(dailydata)
eurdaily=ts(dailydata,start=2020,freq=366)
plot(eurdaily)
acf(eurdaily)
pacf(eurdaily)
acf(diff(eurdaily))
eurdaily.diff=diff(eurdaily)
plot(eurdaily.diff)
library(tseries)
adf.test(eurdaily.diff)
pacf(eurdaily.diff)
library(forecast)
auto.arima(eurdaily)
model.daily=arima(eurdaily,order=c(1,1,0))
Box.test(eurdaily,type="Ljung-Box")
Box.test(eurdaily,type='Box-Pierce')
model.daily.forcast.1day=forecast(model.daily,h=1)
plot(model.daily.forcast.1day)
model.daily.forcast.1month=forecast(model.daily,h=30)
plot(model.daily.forcast.1month)
model.daily.forcast.3month=forecast(model.daily,h=90)
plot(model.daily.forcast.3month)
model.daily.forcast.6month=forecast(model.daily,h=180)
plot(model.daily.forcast.6month)
model.daily.forcast.12month=forecast(model.daily,h=365)
plot(model.daily.forcast.12month)
dailymodel.summary=summary(model.daily)
rmse.dailymodel=dailymodel.summary[2]
mse.dailymodel=rmse.dailymodel^2
print(mse.dailymodel)
```


```{r,warning=FALSE,message=FALSE}
weeklydata=read.table('eurweekly.txt')
attach(weeklydata)
eurweekly=ts(weeklydata,start=2020,freq=52)
plot(eurweekly)
acf(eurweekly)
pacf(eurweekly)
acf(diff(eurweekly))
eurweekly.diff=diff(eurweekly)
plot(eurweekly.diff)
library(tseries)
adf.test(eurweekly.diff)
pacf(eurweekly.diff)
library(forecast)
auto.arima(eurweekly)
model.weekly=arima(eurweekly,order=c(0,1,0))
Box.test(eurweekly,type="Ljung-Box")
Box.test(eurweekly,type='Box-Pierce')
model.weekly.forcast.1month=forecast(model.weekly,h=4)
plot(model.weekly.forcast.1month)
model.weekly.forcast.3month=forecast(model.weekly,h=12)
plot(model.weekly.forcast.3month)
model.weekly.forcast.6month=forecast(model.weekly,h=24)
plot(model.weekly.forcast.6month)
model.weekly.forcast.12month=forecast(model.weekly,h=52)
plot(model.weekly.forcast.12month)
weeklymodel.summary=summary(model.weekly)
rmse.weeklymodel=weeklymodel.summary[2]
mse.weeklymodel=rmse.weeklymodel^2
print(mse.weeklymodel)
```


